### ISSUE TITLE
Collaboration 

### ISSUE THREAD

**Issue by NullDivision** [cowboy/node-globule#28]
Hello @cowboy,

Due to the lack of activity for the past two years on the project I have recently opened an issue on NPM to receive access to the package. 

If granted I would be able to fix, extend and improve the package greatly given the recent improvements. 

Please take into consideration my request and hope to hear from you soon.

**Comment by cowboy** [comment]
@tkellen @jonschlinkert I remember some discussion a while back about contributing to this module. Do either of you have any interest or opinion on adding @NullDivision as a maintainer / npm owner?

@NullDivision have you seen the `async` branch? I did some substantial refactoring there (the work was pretty much finished) that I never got to merge in. Also, if memory serves, @jonschlinkert wrote another globbing module that's significantly faster than this one.

**Comment by tkellen** [comment]
I'm :+1:!

For what it is worth, I immediately give commit bit to anyone who submits a PR of good quality on an open source library I've created.

**Comment by jonschlinkert** [comment]
> I immediately give commit bit to anyone who submits a PR of good quality on an open source library I've created.

Same! although I would add the caveat that when a library is as heavily used as this, I personally ask for peer review before merging/publishing. but that's my own preference.

> Also, if memory serves, @jonschlinkert wrote another globbing module that's significantly faster than this one.

you might be thinking of [micromatch](https://github.com/jonschlinkert/micromatch), but it doesn't do any fs stuff, just the matching.

**Comment by NullDivision** [comment]
Yes, but given recent changes in dependency architecture (see Lodash) it makes sense to update the project. Also, there are issues open, suggestions to merge and newly integrated libraries in Node itself.

I agree @jonschlinkert, peer review is a huge part of it as well as testing. And naturally I don't intend to change anything of the functionality. But exactly **because** it's such a widely used package is why it should remain stable and up to date for future releases.

There's also other things that can be done. Stable ES6 integration, typechecking or even workers to handle larger loads.

And yes, all of these would obviously go through revision and rigorous testing.

**Comment by cowboy** [comment]
Sorry for the delay, I'm right in the middle of moving. @NullDivision, are you interested in just maintaining the project and closing issues, or do you have ideas for the future of the project past maintenance? Also, have you seen the "async" branch? I put a lot of effort into making the library work both sync and async, but was never able to publish it. Ideally, all future work would be done based on that branch.

**Comment by cowboy** [comment]
I just pushed some WIP `example.md` building code to the async branch. If you want to see what it the async branch can do, check out [examples/find-event-emitter.js](https://github.com/cowboy/node-globule/blob/async/examples/find-event-emitter.js). Imagine the kind of visual feedback people will be able to utilize if this approach is used inside Grunt, for example.

**Comment by NullDivision** [comment]
I'm interested in improvements as well. :) And yes, I saw the branch and was curious as well about why it wasn't already implemented when going through the master branch so it was one of my first ideas as well.

**Comment by NullDivision** [comment]
Have you considered Bluebird as promise-based lookups?

**Comment by cowboy** [comment]
@NullDivision can you create an issue outlining the improvements you'd like to implement? I'm all for getting you in here to contribute, I'd just love to see a plan first.

**Comment by cowboy** [comment]
@vladikoff @shama do either of you have any interest in helping maintain this project?

**Comment by jonschlinkert** [comment]
@cowboy I'd be happy to at least help get globule up-to-date if @vladikoff and @shama don't have time. IMHO it would be good to start with just updates and optimizing the code without changing the current API. up to you guys, I won't be offended either way

**Comment by shama** [comment]
@cowboy Yep! I can help out.

**Comment by shama** [comment]
Closing as the project is active now. Thanks!
