### ISSUE TITLE
Globule requires outdated version of lodash

### ISSUE THREAD

**Issue by simplegadget512** [cowboy/node-globule#42]
[Nodesecurity](https://nodesecurity.io/advisories/577) reports there is an issue with prototype pollution in the version of lodash that you are requiring.

**Comment by PhilippeVay** [comment]
This issue is a duplicate of #41.  
As stated by @shama there, [package.json uses "lodash": "~4.17.4",](https://github.com/cowboy/node-globule/blob/master/package.json#L47) which is 4.17.x thus 4.17.10 to date (lodash is fine since 4.17.5 included)

**Comment by shama** [comment]
@PhilippeVay is correct but I'll go ahead and update anyways to avoid people continually opening issues: https://github.com/cowboy/node-globule/commit/b2f8ce0f31d011baafc93a9fb13530b5e23deab7
