### ISSUE TITLE
npm audit high vulnerability issue

### ISSUE THREAD

**Issue by Cherviakov** [cowboy/node-globule#44]
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ node-sass                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ node-sass > gaze > globule > lodash                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/782                             │
└───────────────┴──────────────────────────────────────────────────────────────┘

```

**Comment by shama** [comment]
lodash is tagged in this project with `~4.17.10` which means it will install the latest patch including `4.17.11`. Please update your dependencies, remove your `package-lock.json` and `npm install` again.

**Comment by evanhooff** [comment]
Hi @shama,
Globule itself includes lodash with version ~4.17.10. I checked the package.lock of globule itself:
https://github.com/cowboy/node-globule/blob/master/package.json 
So removing/updating does not fix this problem.
This issue is not closed, globule needs to be updated to use lodash version 4.17.12+: 
https://www.npmjs.com/advisories/1065

**Comment by vladikoff** [comment]
https://github.com/cowboy/node-globule/blob/master/package.json#L47

![image](https://user-images.githubusercontent.com/128755/61469099-a1e10c80-a94c-11e9-9793-a5facb2c3045.png)

**Comment by shama** [comment]
I also did a fresh install of globule to double check as well and it installed `lodash@4.17.14` as expected:
![Screen Shot 2019-07-18 at 9 03 47 AM](https://user-images.githubusercontent.com/99604/61473388-2a56b180-a93b-11e9-8511-0e010efdc2fc.png)

**Comment by evanhooff** [comment]
Yes I understand, thank you for your answer.
I see the original ticket also mentioned gaze so that's probably the issue.
