### ISSUE TITLE
Fix security issue caused by node-globule

### ISSUE THREAD

**Issue by alexanderyarm** [cowboy/node-globule#45]
We have security issue in our project due to old version of `lodash` which `node-globule` has as a dependency.

Please look at the screenshot.

![Screenshot 2019-12-19 at 16 40 53](https://user-images.githubusercontent.com/2443817/71188320-064c2300-2281-11ea-8492-9c80104efac4.png)

Please update lodash at least to the version `4.17.12` as `node-globule` is a transitive dependency of `node-sass` and it's very critical

`node-sass` depends on `gaze` and `gaze` depends on `node-globule`

**Comment by voxxit** [comment]
@alexanderyarm It would seem that [the `package-lock.json` in the 1.3.0 release](https://github.com/cowboy/node-globule/blob/master/package-lock.json#L1528-L1532) (still on master, but as of yet unpublished) has this already in it. 

@cowboy @vladikoff Were you guys planning to release this soon? Thanks! 💯

**Comment by vladikoff** [comment]
It should be in 1.3.0 from 9 days ago?

**Comment by voxxit** [comment]
@vladikoff unfortunately, the NPM package you shipped does not include the same `package-lock.json` file that is included in the repo. Perhaps that is needed?

**Comment by andressantiago** [comment]
@vladikoff @cowboy any updates on when a `lodash` `4.17.12` or higher will be included in released? 

Thank you in advance.

**Comment by vladikoff** [comment]
Published 1.3.1 forcefully bumping lodash, make sure to properly update your lock files!
