### ISSUE TITLE
lodash dependency still at 4.17.10 which has vunerabilities

### ISSUE THREAD

**Issue by careylew** [cowboy/node-globule#52]
Is it possible to update the lodash dependency to 4.17.20?

Right now it's :
    lodash "~4.17.10"

https://snyk.io/test/npm/lodash/4.17.10

**Comment by fylzero** [comment]
Submitted a PR to address this:  https://github.com/cowboy/node-globule/pull/59

**Comment by nharrisanalyst** [comment]
can this PR get Merged 
Thank You
